require 'bundler/setup'
Bundler.require
require 'sinatra/base'
require 'haml'
require 'json'
require 'sequel'
require 'bcrypt'
require 'sendgrid-ruby'

require 'fluffy_paws/version'
require 'fluffy_paws/helpers'
require 'fluffy_paws/models'
require 'fluffy_paws/mailers'
require 'fluffy_paws/repositories/user'
require 'fluffy_paws/repositories/login_token'
require 'fluffy_paws/interactions/login'
require 'fluffy_paws/interactions/register'
require 'fluffy_paws/interactions/login_with_email'
require 'fluffy_paws/interactions/authorize_token'
require 'fluffy_paws/app'
